export const GET_ALL_TV_SHOWS_REQUEST = "GET_ALL_TV_SHOWS_REQUEST";
export const GET_ALL_TV_SHOWS_SUCCESS = "GET_ALL_TV_SHOWS_SUCCESS";
export const GET_ALL_TV_SHOWS_FAILURE = "GET_ALL_TV_SHOWS_FAILURE";
