export const SHOW_DETAILS_REQUEST_START = "SHOW_DETAILS_REQUEST_START";
export const SHOW_DETAILS_REQUEST_SUCCESS = "SHOW_DETAILS_REQUEST_SUCCESS";
export const SHOW_DETAILS_REQUEST_FAILURE = "SHOW_DETAILS_REQUEST_FAILURE";
