export const START_TV_SHOW_FETCHING = "START_TV_SHOW_FETCHING";
export const GET_ALL_TV_SHOWS_SUCCESS = "GET_ALL_TV_SHOWS_SUCCESS";
export const GET_ALL_TV_SHOWS_FAILURE = "GET_ALL_TV_SHOWS_FAILURE";
