export const genresOptions = [
  { value: "all shows", label: "All Shows" },
  { value: "drama", label: "Drama" },
  { value: "horror", label: "Horror" },
  { value: "comedy", label: "Comedy" },
  { value: "science-fiction", label: "Science-Fiction" },
  { value: "romance", label: "Romance" },
  { value: "thriller", label: "Thriller" },
  { value: "action", label: "Action" },
  { value: "crime", label: "Crime" },
  { value: "adventure", label: "Adventure" },
  { value: "mystery", label: "Mystery" },
  { value: "family", label: "Family" },
  { value: "supernatural", label: "Supernatural" },
  { value: "anime", label: "Anime" },
  { value: "fantasy", label: "Fantasy" },
  { value: "history", label: "History" },
];
